# vim: ft=python
Import('env')
Import('Lib')

out = env.Program(
    target='my_program',
    source=[
        'main.cpp',
        Lib(':hello_helper'),  # Same SConscript (see below)
        Lib('//util:util'),    # Different SConscript
    ],
)

env.Library(
    target='hello_helper',
    source=['HelloHelper.cpp'],
)

Return('out')
